### ISSUE TITLE
please add a good example for caching

### ISSUE THREAD

**Issue by RaSan147** [ArtemSBulgakov/buildozer-action#19]
There is a example for caching but not explained where to put it.

I'm using the fork of this repo, putting the cache part in anywhere in job section in the build.yml fails to cache since the main buildozer job is auto cleaning the files

**Comment by ArtemSBulgakov** [comment]
Hi. You can see example in https://github.com/kivymd/KitchenSink/blob/86b08cb248686e8a50cfd31dbdab521597b8e8cc/.github/workflows/main.yml#L24-L33

There are caching for global and local .buildozer directories.

**Comment by RaSan147** [comment]
Thanks
