### ISSUE TITLE
Unable to use buildozer-action

### ISSUE THREAD

**Issue by thesparkvision** [ArtemSBulgakov/buildozer-action#6]
Hi, I am new in the kivy deployment part. My system was not supporting .py to .apk conversion because of configuration issues. Today I found out about this github action. I am trying to use on a sample application but not able to perform it right. Is there any tutorial available for that or can you make a sample repository from which I can understand what all values to give to different parameters

**Comment by ArtemSBulgakov** [comment]
Hi. Sorry for my long response.

There is [full workflow example](https://github.com/ArtemSBulgakov/buildozer-action#full-workflow) in the Readme. It is ready to copy. You just need to update workdir.

This repository has workflow that builds test app. You can find workflow file [here](https://github.com/ArtemSBulgakov/buildozer-action/blob/master/.github/workflows/build.yml) and buildozer.spec [here](https://github.com/ArtemSBulgakov/buildozer-action/blob/master/test_app/buildozer.spec).

Also there are [links](https://github.com/ArtemSBulgakov/buildozer-action#examples) to known good examples with complex workflows.

I hope my answer will help you. Write comments if you have any questions.
